### ISSUE TITLE
the website so far 

### ISSUE THREAD

**Issue by Gala4peace** [Gala4peace/Dance-in-Zurich#1]
hello @sophialittlejohn 
Hopefully I've done all the correct steps :) here is where I'm at

**Comment by sophialittlejohn** [comment]
@Gala4peace this looks good! Some of the images won't load though. Make sure you commit any images you've saved locally. e.g `src="Logo-1.png"`
You can store the images in a folder `images/` and then update the `src` in the image tag.

**Comment by Gala4peace** [comment]
shall I upload the image folder as well into github then?

**Comment by sophialittlejohn** [comment]
Yep, just put the images in the `images/` folder

**Comment by Gala4peace** [comment]
cool :) shall do that now
